### PR TITLE
Finishing whitespace fixes

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by davep** [comment]
I generally prefer to keep Makefiles non-untabify for obvious reasons.

**Comment by vszakats** [comment]
I left significant tabs as-is. Only those tabs are significant that are leading the rule commands, the rest can safely be converted to spaces. [ I know there was a belief very early on in Harbour development that suggested that dependency lines must also start with tabs, but this turned out to be wrong after inspecting the manual more closely &mdash; That is, unless you didn't mean something else by obvious reasons. ]

**Comment by davep** [comment]
Sorry, what I meant was, to never cause confusion and to keep things simple, I always keep the `Makefile` a tab-infested hell on purpose. ;)

**Comment by vszakats** [comment]
Ah okay! :)

**Comment by vszakats** [comment]
Tabs restored in `Makefile`.

**Pull request merged**
